# Generated by Django 4.2.6 on 2023-10-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0005_alter_hr_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
